### ISSUE TITLE
Checkboxes are off by one line

### ISSUE THREAD

**Issue by PLNech** [jcontini/google-keep-scraper#1]
From what @jcontini reported on jcontini/facebook-connections-scraper#2:
>One thing I noticed - for notes with checkboxes, the output now puts the checkbox after the text instead of before.

After looking a bit further, it is due to the HTML structure of Google Takeout's notes:
```html
<body>
    <div class="note">
        <div class="heading">7 avr. 2016 &agrave; 21:12:13</div>
        <div class="title">ToMake</div>
        <div class="content">
            <div class="listitem">
                <div class="bullet">&#9744;</div>
                <div class="text">URL Shortner</div>
            </div> 
            <div class="listitem">
                <div class="bullet">&#9744;</div>
                <div class="text">Torrent downloader</div>
            </div>
        </div>
    </div>
</body>
```
As you can see the `bullet` divs are placed _before_ the `text` divs, which explains why `getText()` returns the checkboxes _before_ the associated text. The checkboxes are not after their text, but actually at the end of the _line before_ their text (this is why the first line has only a checkbox and the last line has none).

However, I see no change in jcontini/facebook-connections-scraper#2 that could have caused this change. I can't try the former version as my Takeout data is localised in French, but can you checkout 73a1f9e and run the script to see if the issue was there before my PR? I can't spend more time investigating this for now, but maybe this issue is anterior to those changes?

**Comment by jcontini** [comment]
Closing for now - if still an issue, please feel free to pull request again. Thanks!
